apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
      - name: spark
        image: my-spark-repo/spark:latest
